name: Publish

on:
  release:
    types: [released]

jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Release build
        run: ./gradlew :limbo:assembleRelease

      - name: Source
        run: ./gradlew androidSourcesJar

      - name: Create secrets file
        env:
          MAVEN_PGP_KEY_BASE64_CONTENT: ${{ secrets.MAVEN_PGP_KEY_BASE64_CONTENT }}
          MAVEN_PGP_KEY: ${{ secrets.MAVEN_PGP_KEY }}
        run: sudo bash -c "echo '$MAVEN_PGP_KEY_BASE64_CONTENT' | base64 -d > '$MAVEN_PGP_KEY'"

      - name: Publish to MavenCentral
        run: ./gradlew publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.MAVEN_PGP_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}